"""Generate OmniLSS gRPC Python stubs from proto files.

Usage
-----
python tools/generate_grpc_stubs.py

The preferred path uses ``grpcio-tools``. In constrained development
environments where ``grpcio-tools`` cannot be installed but system ``protoc`` is
available, this script falls back to generating ``*_pb2.py`` with ``protoc`` and
writing small package-relative ``*_pb2_grpc.py`` service wrappers for OmniLSS's
unary services.
"""

from __future__ import annotations

from pathlib import Path
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
PROTO_DIR = ROOT / "src" / "omnilss" / "api" / "grpc" / "proto"
OUT_DIR = ROOT / "src" / "omnilss" / "api" / "grpc" / "generated"
PROTOS = ["capability.proto", "fit.proto", "predict.proto", "sample.proto"]
SERVICE_SPECS = {
    "capability": (
        "CapabilityService",
        (
            ("CapabilityMatrix", "CapabilityMatrixRequest", "CapabilityMatrixResponse"),
            ("RouteCapability", "RouteCapabilityRequest", "RouteCapabilityResponse"),
        ),
    ),
    "fit": ("FitService", (("Fit", "FitRequest", "FitResponse"),)),
    "predict": ("PredictService", (("Predict", "PredictRequest", "PredictResponse"),)),
    "sample": ("SampleService", (("Sample", "SampleRequest", "SampleResponse"),)),
}


def _ensure_init() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    init_file = OUT_DIR / "__init__.py"
    init_file.write_text('"""Generated protobuf modules for OmniLSS gRPC API."""\n')


def _fix_relative_imports() -> None:
    """Make grpcio-tools generated service modules package-relative."""
    for generated in OUT_DIR.glob("*_pb2_grpc.py"):
        text = generated.read_text()
        for proto in PROTOS:
            stem = Path(proto).stem
            text = text.replace(
                f"import {stem}_pb2 as {stem}__pb2",
                f"from . import {stem}_pb2 as {stem}__pb2",
            )
        generated.write_text(text)


def _write_grpc_wrapper(
    stem: str, service: str, methods: tuple[tuple[str, str, str], ...]
) -> None:
    """Write a minimal grpcio-compatible unary service wrapper."""
    stub_lines: list[str] = []
    servicer_lines: list[str] = []
    handler_lines: list[str] = []
    for method, request, response in methods:
        stub_lines.append(
            f"        self.{method} = channel.unary_unary(\n"
            f"            \"/omnilss.{service}/{method}\",\n"
            f"            request_serializer={stem}__pb2.{request}.SerializeToString,\n"
            f"            response_deserializer={stem}__pb2.{response}.FromString,\n"
            f"        )"
        )
        servicer_lines.append(
            f"    def {method}(self, request, context):\n"
            "        context.set_code(grpc.StatusCode.UNIMPLEMENTED)\n"
            "        context.set_details(\"Method not implemented!\")\n"
            "        raise NotImplementedError(\"Method not implemented!\")"
        )
        handler_lines.append(
            f"        \"{method}\": grpc.unary_unary_rpc_method_handler(\n"
            f"            servicer.{method},\n"
            f"            request_deserializer={stem}__pb2.{request}.FromString,\n"
            f"            response_serializer={stem}__pb2.{response}.SerializeToString,\n"
            "        ),"
        )

    (OUT_DIR / f"{stem}_pb2_grpc.py").write_text(
        f'''# Generated by OmniLSS fallback gRPC stub generator. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import {stem}_pb2 as {stem}__pb2


class {service}Stub(object):
    def __init__(self, channel):
{chr(10).join(stub_lines)}


class {service}Servicer(object):
{chr(10).join(servicer_lines)}


def add_{service}Servicer_to_server(servicer, server):
    rpc_method_handlers = {{
{chr(10).join(handler_lines)}
    }}
    generic_handler = grpc.method_handlers_generic_handler(
        "omnilss.{service}", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
'''
    )


def _generate_with_grpc_tools() -> int | None:
    try:
        import grpc_tools.protoc  # noqa: F401
    except Exception:
        return None

    cmd = [
        sys.executable,
        "-m",
        "grpc_tools.protoc",
        "-I",
        str(PROTO_DIR),
        f"--python_out={OUT_DIR}",
        f"--grpc_python_out={OUT_DIR}",
        *[str(PROTO_DIR / p) for p in PROTOS],
    ]
    proc = subprocess.run(cmd, cwd=ROOT)
    if proc.returncode == 0:
        _fix_relative_imports()
    return proc.returncode


def _generate_with_system_protoc() -> int:
    protoc = shutil.which("protoc")
    if protoc is None:
        print(
            "grpcio-tools is unavailable and system protoc was not found. "
            "Install with: pip install 'omnilss[grpc]'",
            file=sys.stderr,
        )
        return 2

    cmd = [
        protoc,
        "-I",
        str(PROTO_DIR),
        f"--python_out={OUT_DIR}",
        *[str(PROTO_DIR / p) for p in PROTOS],
    ]
    proc = subprocess.run(cmd, cwd=ROOT)
    if proc.returncode != 0:
        return proc.returncode

    for stem, (service, methods) in SERVICE_SPECS.items():
        _write_grpc_wrapper(stem, service, methods)
    return 0


def main() -> int:
    _ensure_init()
    result = _generate_with_grpc_tools()
    if result is not None:
        return result

    print(
        "grpcio-tools unavailable; falling back to system protoc for OmniLSS stubs.",
        file=sys.stderr,
    )
    return _generate_with_system_protoc()


if __name__ == "__main__":
    raise SystemExit(main())
