"""Central registry for OmniLSS test suites."""

from __future__ import annotations

from collections import OrderedDict


SUITES: OrderedDict[str, list[str]] = OrderedDict(
    [
        (
            "unit_core",
            [
                "tests.test_operations",
                "tests.test_fixed_parameters",
                "tests.test_cs",
                "tests.test_zip_score_python",
            ],
        ),
        (
            "unit_smoothers",
            [
                "tests.test_bsplines",
                "tests.test_penalties",
                "tests.test_pb",
                "tests.test_ps",
                "tests.test_formula",
                "tests.test_smooth_fitting",
                "tests.test_gamlss_with_smooths",
                "tests.test_gamlss_ml_smooth",
                "tests.test_gamlss_ml_smooth_integration",
            ],
        ),
        (
            "family_batches",
            [
                "tests.test_basic_batch1_remaining",
                "tests.test_basic_batch3_simple",
                "tests.test_basic_batch3",
                "tests.test_basic_batch4",
                "tests.test_basic_batch5",
                "tests.test_basic_batch6_8",
                "tests.test_basic_batch9",
                "tests.test_basic_batch10",
                "tests.test_basic_batch11",
                "tests.test_basic_batch12",
                "tests.test_bug_condition_complex_distributions",
                "tests.test_preservation_complex_distributions",
                "tests.test_pareto2_python_fitting",
                "tests.test_igamma_local_fitting",
            ],
        ),
        (
            "consistency_density",
            [
                "tests.test_consistency_families",
            ],
        ),
        (
            "consistency_basic_fit",
            [
                "tests.test_r_consistency_no",
                "tests.test_r_consistency_po",
                "tests.test_r_consistency_ga",
                "tests.test_r_consistency_logno",
                "tests.test_r_consistency_be",
                "tests.test_r_consistency_beinf",
                "tests.test_r_consistency_bi",
                "tests.test_r_consistency_exp",
                "tests.test_r_consistency_geom",
                "tests.test_r_consistency_ig",
                "tests.test_r_consistency_igamma",
                "tests.test_r_consistency_lo",
                "tests.test_r_consistency_nbi",
                "tests.test_r_consistency_nbii",
                "tests.test_r_consistency_no2",
                "tests.test_r_consistency_logno2",
                "tests.test_r_consistency_pareto2",
                "tests.test_r_consistency_pe",
                "tests.test_r_consistency_rg",
                "tests.test_r_consistency_simplex",
                "tests.test_r_consistency_sn1",
                "tests.test_r_consistency_tf",
                "tests.test_r_consistency_wei",
                "tests.test_r_consistency_zaga",
                "tests.test_r_consistency_zip",
            ],
        ),
        (
            "consistency_advanced_fit",
            [
                "tests.test_r_consistency_batch1_bc",
                "tests.test_r_consistency_batch3_4_remaining",
                "tests.test_r_consistency_batch5",
                "tests.test_r_consistency_batch6",
                "tests.test_r_consistency_batch7_8",
                "tests.test_r_consistency_smooth",
                "tests.test_r_consistency_shash",
                "tests.test_r_consistency_exgaus",
                "tests.test_r_consistency_gt",
                "tests.test_r_consistency_gu",
            ],
        ),
        (
            "consistency_all",
            [
                "tests.test_consistency_families",
                "tests.test_r_consistency_no",
                "tests.test_r_consistency_po",
                "tests.test_r_consistency_ga",
                "tests.test_r_consistency_logno",
                "tests.test_r_consistency_be",
                "tests.test_r_consistency_beinf",
                "tests.test_r_consistency_bi",
                "tests.test_r_consistency_exp",
                "tests.test_r_consistency_geom",
                "tests.test_r_consistency_ig",
                "tests.test_r_consistency_igamma",
                "tests.test_r_consistency_lo",
                "tests.test_r_consistency_nbi",
                "tests.test_r_consistency_nbii",
                "tests.test_r_consistency_no2",
                "tests.test_r_consistency_logno2",
                "tests.test_r_consistency_pareto2",
                "tests.test_r_consistency_pe",
                "tests.test_r_consistency_rg",
                "tests.test_r_consistency_simplex",
                "tests.test_r_consistency_sn1",
                "tests.test_r_consistency_tf",
                "tests.test_r_consistency_wei",
                "tests.test_r_consistency_zaga",
                "tests.test_r_consistency_zip",
                "tests.test_r_consistency_batch1_bc",
                "tests.test_r_consistency_batch3_4_remaining",
                "tests.test_r_consistency_batch5",
                "tests.test_r_consistency_batch6",
                "tests.test_r_consistency_batch7_8",
                "tests.test_r_consistency_smooth",
                "tests.test_r_consistency_shash",
                "tests.test_r_consistency_exgaus",
                "tests.test_r_consistency_gt",
                "tests.test_r_consistency_gu",
            ],
        ),
        (
            "phase0_gate",
            [
                "tests.test_r_consistency_no",
                "tests.test_r_consistency_ga",
                "tests.test_r_consistency_tf",
                "tests.test_r_consistency_be",
                "tests.test_r_consistency_zip",
                "tests.consistency.test_gradient_no_finite_difference",
                "tests.consistency.test_stability_extreme_inputs",
                "tests.test_rs_phase0_diagnostics",
                "tests.test_optimizer_phase0_diagnostics",
            ],
        ),
        (
            "quick",
            [
                "tests.test_operations",
                "tests.test_pb",
                "tests.test_formula",
                "tests.test_gamlss_with_smooths",
                "tests.test_consistency_families",
                "tests.test_r_consistency_no",
                "tests.test_r_consistency_po",
                "tests.test_r_consistency_ga",
                "tests.test_r_consistency_zip",
            ],
        ),
        (
            "all",
            [
                "tests.test_operations",
                "tests.test_fixed_parameters",
                "tests.test_cs",
                "tests.test_zip_score_python",
                "tests.test_bsplines",
                "tests.test_penalties",
                "tests.test_pb",
                "tests.test_ps",
                "tests.test_formula",
                "tests.test_smooth_fitting",
                "tests.test_gamlss_with_smooths",
                "tests.test_gamlss_ml_smooth",
                "tests.test_gamlss_ml_smooth_integration",
                "tests.test_basic_batch1_remaining",
                "tests.test_basic_batch3_simple",
                "tests.test_basic_batch3",
                "tests.test_basic_batch4",
                "tests.test_basic_batch5",
                "tests.test_basic_batch6_8",
                "tests.test_basic_batch9",
                "tests.test_basic_batch10",
                "tests.test_basic_batch11",
                "tests.test_basic_batch12",
                "tests.test_bug_condition_complex_distributions",
                "tests.test_preservation_complex_distributions",
                "tests.test_pareto2_python_fitting",
                "tests.test_igamma_local_fitting",
                "tests.test_fisher_verification",
                "tests.test_consistency_families",
                "tests.test_r_consistency_no",
                "tests.test_r_consistency_po",
                "tests.test_r_consistency_ga",
                "tests.test_r_consistency_logno",
                "tests.test_r_consistency_be",
                "tests.test_r_consistency_beinf",
                "tests.test_r_consistency_bi",
                "tests.test_r_consistency_exp",
                "tests.test_r_consistency_geom",
                "tests.test_r_consistency_ig",
                "tests.test_r_consistency_igamma",
                "tests.test_r_consistency_lo",
                "tests.test_r_consistency_nbi",
                "tests.test_r_consistency_nbii",
                "tests.test_r_consistency_no2",
                "tests.test_r_consistency_logno2",
                "tests.test_r_consistency_pareto2",
                "tests.test_r_consistency_pe",
                "tests.test_r_consistency_rg",
                "tests.test_r_consistency_simplex",
                "tests.test_r_consistency_sn1",
                "tests.test_r_consistency_tf",
                "tests.test_r_consistency_wei",
                "tests.test_r_consistency_zaga",
                "tests.test_r_consistency_zip",
                "tests.test_r_consistency_batch1_bc",
                "tests.test_r_consistency_batch3_4_remaining",
                "tests.test_r_consistency_batch5",
                "tests.test_r_consistency_batch6",
                "tests.test_r_consistency_batch7_8",
                "tests.test_r_consistency_smooth",
                "tests.test_r_consistency_shash",
                "tests.test_r_consistency_exgaus",
                "tests.test_r_consistency_gt",
                "tests.test_r_consistency_gu",
            ],
        ),
    ]
)


SUITE_ALIASES = {
    "unit": "unit_core",
    "smoothers": "unit_smoothers",
    "consistency": "consistency_all",
    "phase0": "phase0_gate",
}


def resolve_suite_name(name: str) -> str:
    return SUITE_ALIASES.get(name, name)


def get_suite_modules(name: str) -> list[str]:
    resolved = resolve_suite_name(name)
    if resolved not in SUITES:
        available = ", ".join(SUITES)
        raise KeyError(f"Unknown suite '{name}'. Available suites: {available}")
    return list(SUITES[resolved])
